### ISSUE TITLE
Página de erro

### ISSUE THREAD

**Issue by Eilem** [dindigital/Din-Style#3]
- Todo projeto deve ter uma página de erro 404.

No padrão do laravel a página de erro deve ficar em:   `./resources/errors/`  com o nome de **404**

**Comment by Eilem** [comment]
@Fnks @nncl

**Comment by nncl** [comment]
@Eilem 👍

**Comment by nncl** [comment]
@Eilem @mariosmello @Fnks 

Adicionamos uma descrição na documentação do Din Style. Veja mais [aqui](https://github.com/dindigital/style-patterns/wiki#p%C3%A1gina-de-erro---404).

Fecharei a issue como resolvida 👍
